### ISSUE TITLE
CI/automated testing

### ISSUE THREAD

**Issue by DanNixon** [david-mathews-1994/deltarice#3]
Ideally it would be good to see compilation and some form of round trip testing (even if relatively minimal) done automatically.

**Comment by david-mathews-1994** [comment]
I'm working on a new set of tests in this branch: https://github.com/david-mathews-1994/deltarice/tree/tests. Mostly I'm working on making the C++ and Python test scripts more robust (Python is done, working on C++), and once those are fully testing the library properly I'll work on automating the routine.

**Comment by david-mathews-1994** [comment]
In theory this has been resolved! I did a bit of testing and like you said, it wasn't super hard to set up. It runs a series of tests on Ubuntu and MacOS and goes through and runs the pythonTesting.py script to ensure it properly behaves. That script also has been modified to make sure that all of the possible input values are treated properly.
